import type { ConversationMessageRecord, PersistCaptureImageInput, SessionRecord, SessionStorage } from "./types";
export declare class FileSessionStorage implements SessionStorage {
    readonly baseDir: string;
    private readonly capturesDir;
    private readonly sessionsDir;
    private readonly indexPath;
    private pendingWrite;
    constructor(baseDir: string);
    createSession(record: SessionRecord): Promise<void>;
    updateSession(sessionId: string, updates: Partial<SessionRecord>): Promise<void>;
    deleteSession(sessionId: string): Promise<void>;
    appendConversationMessage(message: ConversationMessageRecord): Promise<void>;
    replaceConversationMessage(messageId: string, message: ConversationMessageRecord): Promise<void>;
    getSession(sessionId: string): Promise<SessionRecord | null>;
    getConversation(sessionId: string): Promise<ConversationMessageRecord[]>;
    listSessions(): Promise<SessionRecord[]>;
    persistCaptureImage(input: PersistCaptureImageInput): Promise<string>;
    getCaptureImageDataUrl(relativePath: string): Promise<string>;
    private enqueueWrite;
    private readSessionIndex;
    private writeSessionIndex;
    private readConversation;
    private writeConversation;
    private getConversationPath;
    private getCaptureDirectoryPath;
    private resolveStoragePath;
    private readJsonFile;
    private writeJsonFile;
    private isMissingFileError;
}
