import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowLeft, Sparkles } from 'lucide-react';
import SessionHistoryCard from './SessionHistoryCard';
export default function AllSessionsPage({ onBack, onDeleteSession, onSelectSession, sessions, }) {
    return (_jsx("div", { className: "ocean-gradient relative min-h-screen text-[var(--text-primary)]", children: _jsxs("div", { className: "mx-auto flex min-h-screen max-w-5xl flex-col px-8 py-10", children: [_jsxs("header", { className: "flex items-start justify-between gap-6", children: [_jsxs("div", { children: [_jsxs("button", { className: "inline-flex cursor-pointer items-center gap-2 rounded-full border border-[var(--border-soft)] bg-[var(--bg-surface)] px-4 py-2 text-sm font-medium text-[var(--text-secondary)] shadow-sm transition hover:border-[var(--primary)] hover:text-[var(--primary)]", onClick: onBack, type: "button", children: [_jsx(ArrowLeft, { size: 16 }), "Back"] }), _jsx("h1", { className: "mt-3 font-display text-4xl font-semibold text-[var(--text-primary)]", children: "All Sessions" }), _jsx("p", { className: "mt-3 max-w-2xl text-base leading-7 text-[var(--text-secondary)]", children: "Browse your previous sessions with Delfin and keep a clear sense of what you worked through over time." })] }), _jsxs("div", { className: "rounded-2xl border border-[var(--border-soft)] bg-[var(--bg-surface)] px-5 py-4 shadow-sm", children: [_jsx("p", { className: "text-xs font-medium uppercase tracking-[0.22em] text-[var(--text-muted)]", children: "Total Sessions" }), _jsx("p", { className: "mt-2 text-3xl font-semibold text-[var(--text-primary)]", children: sessions.length })] })] }), _jsx("main", { className: "mt-8 flex-1", children: sessions.length === 0 ? (_jsxs("div", { className: "flex min-h-[24rem] flex-col items-center justify-center rounded-[2rem] border border-dashed border-[var(--border-soft)] bg-[var(--bg-surface)]/70 px-8 text-center", children: [_jsx("div", { className: "flex h-16 w-16 items-center justify-center rounded-full bg-[var(--primary-soft)] text-[var(--primary)]", children: _jsx(Sparkles, { size: 28 }) }), _jsx("h2", { className: "mt-5 font-display text-2xl font-semibold text-[var(--text-primary)]", children: "No sessions yet" }), _jsx("p", { className: "mt-3 max-w-md text-sm leading-6 text-[var(--text-secondary)]", children: "Start a session with Delfin and your study history will appear here." })] })) : (_jsx("div", { className: "grid gap-4 md:grid-cols-2", children: sessions.map((session) => (_jsx(SessionHistoryCard, { onDelete: () => {
                                onDeleteSession(session.id);
                            }, onClick: () => {
                                onSelectSession(session.id);
                            }, session: session }, session.id))) })) })] }) }));
}
