// IPC channel names (as const for type safety)
export const RENDERER_TO_MAIN_CHANNELS = {
    CAPTURE_NOW: 'capture:now',
    CAPTURE_AUTO_REFRESH: 'capture:auto-refresh',
    SIDECAR_SEND: 'sidecar:send',
    SIDECAR_INTERRUPT: 'sidecar:interrupt',
    OVERLAY_GET_STATE: 'overlay:get-state',
    OVERLAY_MINIMIZE: 'overlay:minimize',
    OVERLAY_RESTORE: 'overlay:restore',
    OVERLAY_SET_MINIMIZED_VARIANT: 'overlay:set-minimized-variant',
    OVERLAY_CLEAR_ENDED_SESSION: 'overlay:clear-ended-session',
    SESSION_START: 'session:start',
    SESSION_STOP: 'session:stop',
    SESSION_SUBMIT_PROMPT: 'session:submit-prompt',
    SESSION_LIST: 'session:list',
    SESSION_GET_DETAIL: 'session:get-detail',
    SESSION_DELETE: 'session:delete',
    SESSION_GET_MESSAGE_IMAGE: 'session:get-message-image',
};
export const MAIN_TO_RENDERER_CHANNELS = {
    FRAME_CAPTURED: 'frame:captured',
    OVERLAY_ERROR: 'overlay:error',
    SIDECAR_TOKEN: 'sidecar:token',
    SIDECAR_AUDIO_START: 'sidecar:audio_start',
    SIDECAR_AUDIO_CHUNK: 'sidecar:audio_chunk',
    SIDECAR_AUDIO_END: 'sidecar:audio_end',
    SIDECAR_DONE: 'sidecar:done',
    SIDECAR_ERROR: 'sidecar:error',
    SIDECAR_STATUS: 'sidecar:status',
};
